### ISSUE TITLE
`strict_max_version` at 56 but expected to be compatible with 57

### ISSUE THREAD

**Issue by mcomella** [eryw/firefox-simple-blocker#1]
From an addons.mozilla.org review:

> It's currently got a strict_max_version set to Firefox 56 in the manifest. Which prevents it loading in Firefox 57. Is there a reason for that? You can just remove that line from the manifest and it will work on all future Firefox versions.

I'm unable to use this add-on in FF57 (Beta) because of this!

**Comment by eryw** [comment]
Thanks for pointing this out.

**Comment by eryw** [comment]
Commit bf951de80dcb43213648d27b553d4cd9c4dda412
