### ISSUE TITLE
js error in version 0.3.6

### ISSUE THREAD

**Issue by kar8nga** [eryw/firefox-simple-blocker#4]
In version 0.3.6 of 12 December the browser console shows the following error:

background is null

raised at line 11 in options.js. That means in the expression

 background.save(document.querySelector('#regexes').value,
      document.querySelector('input[name="mode"]:checked').value,
      document.querySelector('input[name="debugging"]:checked').value
    )

within the tout function.

**Comment by eryw** [comment]
Which Firefox version you're using?

**Comment by kar8nga** [comment]
Sorry for the delay, have been sick for two days.

the error was on
57.0.1+build2-0ubuntu0.17.10.1 (64bit Ubuntu 17.10)
but autosaving of regexes and blocking works on
57.0.1 (32bit Ubuntu 14.04 LTS)

**Comment by kar8nga** [comment]
The issue is solved by realising my own error: when in private browsing mode, changes to the addons settings do not persist. That is why the error seemed so random and unexplainable to me. Thanks for taking the time to look at this and for creating this addon -- it helps me a lot.
